#!/usr/bin/env python3
"""Query Overpass API for EV charging stations in Tunisia and generate SQL INSERT."""

import json
import urllib.request
import urllib.parse
import sys
import os

OVERPASS_URL = "https://overpass-api.de/api/interpreter"
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "migrations")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "003_seed_stations.sql")

QUERY = """
[out:json];
(
  node["amenity"="charging_station"](34.0,7.0,38.0,12.0);
  way["amenity"="charging_station"](34.0,7.0,38.0,12.0);
  rel["amenity"="charging_station"](34.0,7.0,38.0,12.0);
);
out center;
"""


def query_overpass() -> list:
    data = urllib.parse.urlencode({"data": QUERY.strip()}).encode("utf-8")
    req = urllib.request.Request(OVERPASS_URL, data=data)
    print("  Querying Overpass API for Tunisia charging stations...")
    response = urllib.request.urlopen(req, timeout=120)
    result = json.loads(response.read().decode("utf-8"))
    return result.get("elements", [])


def generate_sql(elements: list) -> str:
    lines = [
        "-- Generated by query_overpass.py from OpenStreetMap Overpass API",
        "-- Source: Tunisia, amenity=charging_station (nodes, ways, relations)",
        "-- License: ODbL 1.0",
        "",
    ]

    seen_ids = set()
    insert_lines = []
    station_id = 0

    for el in elements:
        osm_id = str(el.get("id", ""))
        type_prefix = el.get("type", "node")[0].upper()
        dedup_key = f"{type_prefix}{osm_id}"
        if dedup_key in seen_ids:
            continue
        seen_ids.add(dedup_key)

        tags = el.get("tags", {})
        lat = el.get("lat")
        lon = el.get("lon")

        if lat is None or lon is None:
            center = el.get("center", {})
            lat = center.get("lat")
            lon = center.get("lon")

        if lat is None or lon is None:
            continue

        station_id += 1
        sid = f"STA-{station_id:05d}"
        name = tags.get("name", "") or tags.get("operator", "") or ""
        safe_name = name.replace("'", "''") if name else sid

        tags_str = " | ".join(f"{k}={v}" for k, v in sorted(tags.items()) if k in ("amenity", "operator", "brand", "name"))
        insert_lines.append(f"-- OSM {el.get('type')} {osm_id}: {tags_str}")
        insert_lines.append(
            f"INSERT INTO inventory.station "
            f"(id, name, status, latitude, longitude, location) "
            f"VALUES "
            f"('{sid}', '{safe_name}', 'active', "
            f"{lat}, {lon}, "
            f"ST_SetSRID(ST_MakePoint({lon}, {lat}), 4326)::geography);"
        )

    lines.extend(insert_lines)
    lines.append("")
    lines.append(f"-- Total stations inserted: {station_id}")
    return "\n".join(lines)


def main():
    print("Querying OpenStreetMap for EV charging stations in Tunisia...")

    try:
        elements = query_overpass()
    except urllib.error.HTTPError as e:
        print(f"  ERROR: HTTP {e.code}: {e.reason}", file=sys.stderr)
        body = e.read().decode("utf-8", errors="replace")
        print(f"  Body: {body[:300]}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"  Found {len(elements)} charging station(s)")

    if not elements:
        print("  WARNING: No stations found.")
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(OUTPUT_FILE, "w") as f:
            f.write("-- No charging stations found in Tunisia OSM data.\n")
        sys.exit(0)

    sql = generate_sql(elements)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    with open(OUTPUT_FILE, "w") as f:
        f.write(sql)

    station_count = sql.count("INSERT INTO inventory.station")
    print(f"  Generated {station_count} INSERT statements")
    print(f"  Output: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
