#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INPUT_FILE="${SCRIPT_DIR}/charging_stations.osm.pbf"
MIGRATIONS_DIR="${SCRIPT_DIR}/../migrations"
OUTPUT_FILE="${MIGRATIONS_DIR}/003_seed_stations.sql"

if [ ! -f "${INPUT_FILE}" ]; then
    echo "ERROR: Input file not found: ${INPUT_FILE}"
    echo "Run filter.sh first to create the filtered OSM data."
    exit 1
fi

echo "Converting filtered OSM data to SQL INSERT format..."
echo "  Input: ${INPUT_FILE}"
echo "  Output: ${OUTPUT_FILE}"

mkdir -p "${MIGRATIONS_DIR}"

cat > "${OUTPUT_FILE}" << 'SQL_HEADER'
-- Generated by transform.sh from OpenStreetMap Tunisia extract
-- Source: https://download.geofabrik.de/africa/tunisia-latest.osm.pbf
-- Filter: amenity=charging_station
-- License: ODbL 1.0

SQL_HEADER

ogr2ogr -f "PGDump" \
    "/tmp/charging_stations_dump.sql" \
    "${INPUT_FILE}" \
    -lco GEOMETRY_NAME=location \
    -lco LAUNDER=yes \
    -nln "inventory.station" \
    -nlt "POINT" \
    -s_srs EPSG:4326 \
    -t_srs EPSG:4326 \
    2>/dev/null || true

if [ -f "/tmp/charging_stations_dump.sql" ]; then
    # Parse ogr2ogr output into our schema format
    python3 -c "
import re
import sys

seen_ids = set()
insert_count = 0
station_id = 0

with open('/tmp/charging_stations_dump.sql', 'r') as f:
    content = f.read()

# Extract INSERT statements
for match in re.finditer(r'INSERT INTO \"inventory\"\.\"station\"\s*\((.*?)\)\s*VALUES\s*(.*?);', content, re.DOTALL):
    values_text = match.group(2)
    # Parse individual value tuples
    for val_match in re.finditer(r'\((.*?)\)', values_text, re.DOTALL):
        vals = val_match.group(1)
        parts = [p.strip().strip(\"'\") for p in vals.split(',')]

        if len(parts) < 2:
            continue

        osm_id = parts[0] if len(parts) > 0 else ''
        name = parts[1] if len(parts) > 1 else ''
        geom_wkt = parts[-1] if len(parts) > 2 else ''

        # Skip duplicates
        if osm_id in seen_ids:
            continue
        seen_ids.add(osm_id)

        # Extract lat/lon from POINT(x y) WKT
        point_match = re.search(r'POINT\s*\(([\d\.\-]+)\s+([\d\.\-]+)\)', geom_wkt, re.IGNORECASE)
        if point_match:
            lon = float(point_match.group(1))
            lat = float(point_match.group(2))
        else:
            continue

        station_id += 1
        sid = f'STA-{station_id:05d}'
        safe_name = name.replace(\"'\", \"''\") if name else sid

        print(f\"INSERT INTO inventory.station (id, name, status, latitude, longitude, location) VALUES ('{sid}', '{safe_name}', 'active', {lat}, {lon}, ST_SetSRID(ST_MakePoint({lon}, {lat}), 4326)::geography);\")
        insert_count += 1

print(f'-- Total stations inserted: {insert_count}', file=sys.stderr)
" >> "${OUTPUT_FILE}" 2>&1

    rm -f /tmp/charging_stations_dump.sql
else
    echo "-- No stations found in OSM data. Creating empty seed file." >> "${OUTPUT_FILE}"
    echo "-- This may indicate the filter found 0 charging stations." >> "${OUTPUT_FILE}"
fi

echo ""
echo "Transform complete. Output file: ${OUTPUT_FILE}"
echo "Total stations: $(grep -c 'INSERT INTO inventory.station' "${OUTPUT_FILE}" || echo 0)"
