export const ErrorCodes = [
  'UNAUTHENTICATED',
  'FORBIDDEN',
  'TOKEN_EXPIRED',
  'PARTNER_SCOPE_VIOLATION',
  'INSUFFICIENT_ROLE',
  'NOT_FOUND',
  'ALREADY_EXISTS',
  'SOFT_DELETED',
  'VALIDATION_FAILED',
  'INVALID_COORDINATES',
  'INVALID_STATE_TRANSITION',
  'ACTIVE_STATIONS_EXIST',
  'REVIEW_STATE_INVALID',
] as const;

export type ErrorCode = typeof ErrorCodes[number];
