[package]
name = "test_v01"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
csv-async = { version = "1", features = ["tokio"] }
serde = { version = "1.0.217", features = ["derive"] }