TRUNCATE TABLE users.station_review CASCADE;
TRUNCATE TABLE users.favorite_station CASCADE;
TRUNCATE TABLE users.partner_membership CASCADE;
TRUNCATE TABLE users.user_profile CASCADE;
TRUNCATE TABLE users.user_account CASCADE;
TRUNCATE TABLE inventory.station_availability CASCADE;
TRUNCATE TABLE inventory.charger CASCADE;
TRUNCATE TABLE inventory.station CASCADE;
TRUNCATE TABLE inventory.partner CASCADE;
