[package]
name = "test_v04"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
log = "0.4.25"
prometheus = "0.13.4"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
