[package]
name = "test_v05"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
chrono = { version = "0.4.39", features = ["serde"] }
parquet = "54.0.0"
