[package]
name = "admin-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
common-observability = { path = "../../crates/common-observability" }
common-config = { path = "../../crates/common-config" }
envy = { workspace = true }
sqlx = { workspace = true }
