customers:
  - customer_type: "home"
    cc_ndc:
      - cc: "+216"
        ndc: [30, 31, 32]
        perc: 40
      - cc: "+216"
        ndc: [50, 51, 52, 53]
        mcc: 603
        mnc: 11
        perc: 60
    digits: 6
    count: 1000
  - customer_type: "national"
    cc_ndc:
      - cc: "+216"
        ndc: [20, 21, 23]
      - cc: "+216"
        ndc: [95, 96, 97]
    digits: 6
    count: 1000
  - customer_type: "international"
    cc_ndc:
      - cc: "+330"
        ndc: [6, 5]
      - cc: "+340"
        ndc: [6, 5]
      - cc: "+2110"
        ndc: [6, 5]
      - cc: "+2120"
        ndc: [6, 5]
    digits: 8
    count: 1000