[package]
name = "test_v04"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
sled = "0.34"
tokio = { version = "1.43.0", features = ["full"] }
