[package]
name = "cdr_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
csv = "1"
serde_json = "1"
bincode = "1"
asn1_der = "0.6"