[package]
name = "work"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
datafusion = "44.0.0"  
tokio = { version = "1.43.0", features = ["full"] }
arrow = "44.0.0" 
uuid = { version = "1.3", features = ["v4"] }
chrono = "0.4"
deltalake = "0.23.2"
