[package]
name = "test_v02"
version = "0.1.0"
edition = "2021"

[dependencies]

serde_json = "1.0.137"
sled = "0.34.7"
thiserror = "2.0.11"

serde = { version = "1.0.217", features = ["derive"] }
chrono = "0.4.39"
rand = "0.8.5"
