[package]
name = "test_v05"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "44.0.0"
tokio = { version = "1.43.0", features = ["full"] }
uuid = { version = "1.12.1", features = ["v4"] }
