[package]
name = "queue"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.21.2", features = ["full"] }