[workspace]
resolver = "2"
members = [
    "services/libs/borne-data",
    "services/driver-service",
    "services/clickstream-service",
    "crates/ev-core",
    "crates/ev-db",
    "crates/ev-auth",
]

[workspace.lints.clippy]
style = "warn"
correctness = "warn"
complexity = "warn"
perf = "warn"

[workspace.lints.rust]
unused = "warn"
dead_code = "warn"
