[package]
name = "work"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "54.0.0"
chrono = "0.4.39"
parquet = "54.0.0"
parquet2 = "0.17.2"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }
