http:
  routers:
    driver-api:
      rule: "PathPrefix(`/api/v1/`)"
      service: driver-service
      priority: 100

    web-app:
      rule: "PathPrefix(`/`)"
      service: web-driver
      priority: 10

  services:
    driver-service:
      loadBalancer:
        servers:
          - url: "http://driver-service:3001"

    web-driver:
      loadBalancer:
        servers:
          - url: "http://web-driver:80"
