name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "services/**/*.rs"
      - "services/**/Cargo.toml"
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
  pull_request:
    branches: [main]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "services/**/*.rs"
      - "services/**/Cargo.toml"
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --workspace
      - run: cargo test --workspace
