name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "packages/**/*.ts"
      - "apps/**/*.ts"
      - "apps/**/*.tsx"
  pull_request:
    branches: [main]
    paths:
      - "package.json"
      - "packages/**/*.ts"
      - "apps/**/*.ts"
      - "apps/**/*.tsx"

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build --workspaces --if-present
